# Prerequisites:
# 1. Only one USB network adapter is connected (as it's using a name wildcard)
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      optional: true
    enx:
      match:
        name: "enx*"
      addresses: 
        - $DIRECT_INTERFACE_IP
      optional: true
