#cloud-config

hostname: rpi5

locale: POSIX
timezone: UTC

users:
  - name: rpi5
    groups:
      - sudo
    shell: /bin/bash
    sudo:
      - 'ALL=(ALL) NOPASSWD:ALL'
    ssh_authorized_keys:
      - '$SSH_PUBLIC_KEY'

ssh_pwauth: false

runcmd:
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow from 192.168.1.0/24 to any port ssh
  - ufw allow from $DIRECT_NETWORK to any port ssh
  - ufw --force enable
  - apt-get update
  - apt-get upgrade --assume-yes
  - apt-get install --assume-yes zfsutils-linux
  - apt-get install --assume-yes nvme-cli
  - reboot

bootcmd:
  - mount -o remount,noatime /
